# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalk_geod.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(703, 492)
        self.phi = QtWidgets.QLabel(Dialog)
        self.phi.setGeometry(QtCore.QRect(30, 70, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phi.setFont(font)
        self.phi.setObjectName("phi")
        self.lambda_ = QtWidgets.QLabel(Dialog)
        self.lambda_.setGeometry(QtCore.QRect(16, 100, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lambda_.setFont(font)
        self.lambda_.setObjectName("lambda_")
        self.fi_stopnie_wprowadz = QtWidgets.QLineEdit(Dialog)
        self.fi_stopnie_wprowadz.setGeometry(QtCore.QRect(80, 60, 41, 20))
        self.fi_stopnie_wprowadz.setTabletTracking(False)
        self.fi_stopnie_wprowadz.setAutoFillBackground(False)
        self.fi_stopnie_wprowadz.setObjectName("fi_stopnie_wprowadz")
        self.fi_minuty_wprowadz = QtWidgets.QLineEdit(Dialog)
        self.fi_minuty_wprowadz.setGeometry(QtCore.QRect(130, 60, 41, 20))
        self.fi_minuty_wprowadz.setObjectName("fi_minuty_wprowadz")
        self.fi_sekundy_wprowadz = QtWidgets.QLineEdit(Dialog)
        self.fi_sekundy_wprowadz.setGeometry(QtCore.QRect(180, 60, 113, 20))
        self.fi_sekundy_wprowadz.setObjectName("fi_sekundy_wprowadz")
        self.lambda_stopnie_wprowadz = QtWidgets.QLineEdit(Dialog)
        self.lambda_stopnie_wprowadz.setGeometry(QtCore.QRect(80, 100, 41, 20))
        self.lambda_stopnie_wprowadz.setObjectName("lambda_stopnie_wprowadz")
        self.lambda_minuty_wprowadz = QtWidgets.QLineEdit(Dialog)
        self.lambda_minuty_wprowadz.setGeometry(QtCore.QRect(130, 100, 41, 20))
        self.lambda_minuty_wprowadz.setObjectName("lambda_minuty_wprowadz")
        self.lambda_sekundy_wprowadz = QtWidgets.QLineEdit(Dialog)
        self.lambda_sekundy_wprowadz.setGeometry(QtCore.QRect(180, 100, 113, 20))
        self.lambda_sekundy_wprowadz.setObjectName("lambda_sekundy_wprowadz")
        self.stopnie = QtWidgets.QLabel(Dialog)
        self.stopnie.setGeometry(QtCore.QRect(80, 40, 47, 13))
        self.stopnie.setObjectName("stopnie")
        self.minuty = QtWidgets.QLabel(Dialog)
        self.minuty.setGeometry(QtCore.QRect(130, 40, 47, 13))
        self.minuty.setObjectName("minuty")
        self.sekundy = QtWidgets.QLabel(Dialog)
        self.sekundy.setGeometry(QtCore.QRect(180, 40, 47, 13))
        self.sekundy.setObjectName("sekundy")
        self.pl2000_str5 = QtWidgets.QRadioButton(Dialog)
        self.pl2000_str5.setGeometry(QtCore.QRect(440, 70, 181, 17))
        self.pl2000_str5.setObjectName("pl2000_str5")
        self.pl1992 = QtWidgets.QRadioButton(Dialog)
        self.pl1992.setGeometry(QtCore.QRect(440, 50, 82, 17))
        self.pl1992.setObjectName("pl1992")
        self.x_w_ukladzie = QtWidgets.QLabel(Dialog)
        self.x_w_ukladzie.setGeometry(QtCore.QRect(30, 170, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.x_w_ukladzie.setFont(font)
        self.x_w_ukladzie.setObjectName("x_w_ukladzie")
        self.y_w_ukladzie = QtWidgets.QLabel(Dialog)
        self.y_w_ukladzie.setGeometry(QtCore.QRect(30, 220, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.y_w_ukladzie.setFont(font)
        self.y_w_ukladzie.setObjectName("y_w_ukladzie")
        self.wynik_x_w_ukladzie = QtWidgets.QLabel(Dialog)
        self.wynik_x_w_ukladzie.setGeometry(QtCore.QRect(210, 160, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wynik_x_w_ukladzie.setFont(font)
        self.wynik_x_w_ukladzie.setText("")
        self.wynik_x_w_ukladzie.setObjectName("wynik_x_w_ukladzie")
        self.wynik_y_w_ukladzie = QtWidgets.QLabel(Dialog)
        self.wynik_y_w_ukladzie.setGeometry(QtCore.QRect(190, 210, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wynik_y_w_ukladzie.setFont(font)
        self.wynik_y_w_ukladzie.setText("")
        self.wynik_y_w_ukladzie.setObjectName("wynik_y_w_ukladzie")
        self.x_gk = QtWidgets.QLabel(Dialog)
        self.x_gk.setGeometry(QtCore.QRect(30, 270, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.x_gk.setFont(font)
        self.x_gk.setObjectName("x_gk")
        self.wynik_xgk = QtWidgets.QLabel(Dialog)
        self.wynik_xgk.setGeometry(QtCore.QRect(156, 262, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wynik_xgk.setFont(font)
        self.wynik_xgk.setText("")
        self.wynik_xgk.setObjectName("wynik_xgk")
        self.pl2000_str6 = QtWidgets.QRadioButton(Dialog)
        self.pl2000_str6.setGeometry(QtCore.QRect(440, 90, 131, 17))
        self.pl2000_str6.setObjectName("pl2000_str6")
        self.pl2000_str7 = QtWidgets.QRadioButton(Dialog)
        self.pl2000_str7.setGeometry(QtCore.QRect(440, 110, 141, 17))
        self.pl2000_str7.setObjectName("pl2000_str7")
        self.pl2000_str8 = QtWidgets.QRadioButton(Dialog)
        self.pl2000_str8.setGeometry(QtCore.QRect(440, 130, 131, 17))
        self.pl2000_str8.setObjectName("pl2000_str8")
        self.WGS84 = QtWidgets.QPushButton(Dialog)
        self.WGS84.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.WGS84.setObjectName("WGS84")
        self.GRS80 = QtWidgets.QPushButton(Dialog)
        self.GRS80.setGeometry(QtCore.QRect(320, 90, 75, 23))
        self.GRS80.setObjectName("GRS80")
        self.ygk = QtWidgets.QLabel(Dialog)
        self.ygk.setGeometry(QtCore.QRect(30, 310, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ygk.setFont(font)
        self.ygk.setObjectName("ygk")
        self.xgk_wynik = QtWidgets.QLabel(Dialog)
        self.xgk_wynik.setGeometry(QtCore.QRect(190, 270, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.xgk_wynik.setFont(font)
        self.xgk_wynik.setText("")
        self.xgk_wynik.setObjectName("xgk_wynik")
        self.ygk_wynik = QtWidgets.QLabel(Dialog)
        self.ygk_wynik.setGeometry(QtCore.QRect(130, 320, 511, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ygk_wynik.setFont(font)
        self.ygk_wynik.setText("")
        self.ygk_wynik.setObjectName("ygk_wynik")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.phi.setText(_translate("Dialog", "FI"))
        self.lambda_.setText(_translate("Dialog", "Lambda_"))
        self.stopnie.setText(_translate("Dialog", "Stopnie"))
        self.minuty.setText(_translate("Dialog", "Minuty"))
        self.sekundy.setText(_translate("Dialog", "Sekundy"))
        self.pl2000_str5.setText(_translate("Dialog", "PL-2000 strefa 5"))
        self.pl1992.setText(_translate("Dialog", "PL-1992"))
        self.x_w_ukladzie.setText(_translate("Dialog", "X w układzie:"))
        self.y_w_ukladzie.setText(_translate("Dialog", "Y w układzie:"))
        self.x_gk.setText(_translate("Dialog", "X gk"))
        self.pl2000_str6.setText(_translate("Dialog", "PL-2000 strefa 6"))
        self.pl2000_str7.setText(_translate("Dialog", "PL-2000 strefa 7"))
        self.pl2000_str8.setText(_translate("Dialog", "PL-2000 strefa 8"))
        self.WGS84.setText(_translate("Dialog", "WGS84"))
        self.GRS80.setText(_translate("Dialog", "GRS80"))
        self.ygk.setText(_translate("Dialog", "Y gk"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

